### ISSUE TITLE
Issue using "method='RCTD'" for annotation

### ISSUE THREAD

**Issue by reinertanalytics** [simonwm/tacco#21]
Hello, thanks so much for a great package! I wanted to try running TACCO with method as 'RCTD', however I am running into issues. Specifically, as I understand it, RCTD is now part of 'spacexr' package. I can install spacexr in my environment, but when I try to run this command:

"tc.tl.annotate(adata, adata_50prop, method='RCTD', annotation_key='v2.subclass.l2', result_key='v2.subclass.l2', assume_valid_counts=True,max_annotation = 1)"

I get this error:

"Exception: The conda environment "[/ahg/regevdata/users/jklugham/src/anaconda3/envs/R_RCTD](http://localhost:8888/ahg/regevdata/users/jklugham/src/anaconda3/envs/R_RCTD)" does not exist! A conda environment with a working `RCTD` setup is needed and can be supplied by the `conda_env` argument."

Is this related to the renaming issue, or is something else going on? Any help would be much appreciated!

**Comment by simonwm** [comment]
Hi, glad you like TACCO!
The renaming issue was fixed a while ago here `https://github.com/simonwm/tacco/blob/master/tacco/tools/_RCTD.py#L129` and should not be a problem.
Did you try specifying the conda environment where you installed spacexr as the `conda_env` argument as suggested in the error message? I.e., if you installed it in `~/my/conda/envs/spacexr`, try the extra argument `conda_env="~/my/conda/envs/spacexr"` in your call to `tc.tl.annotate`.

**Comment by reinertanalytics** [comment]
Thank you for your response! Yes, you were right - I was not specifying the conda environment in my call to annotate. Unfortunately I am still seeing an error when I try to use the RCTD wrapper. 

This is the command I am trying to run:

"tc.tl.annotate(
    adata,
    adata_ref,
    method='RCTD',
    conda_env="/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env",
    annotation_key='v2.subclass.l2',
    result_key='v2.subclass.l2',
    assume_valid_counts=True
)"


And here is what I am seeing:

"Starting preprocessing
Finished preprocessing in 1.86 seconds.
Starting annotation of data with shape (65551, 300) and a reference of shape (1388642, 300) using the following wrapped method:
+- multi center: multi_center=None multi_center_amplitudes=True
   +- core: method=RCTD annotation_prior=None conda_env=/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env

[/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/anndata/_core/anndata.py:618](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/anndata/_core/anndata.py#line=617): FutureWarning: You are attempting to set `X` to a matrix on a view which has non-unique indices. The resulting `adata.X` will likely not equal the value to which you set it. To avoid this potential issue, please make a copy of the data first. In the future, this operation will throw an error.
  warnings.warn(msg, FutureWarning, stacklevel=1)

 [1] "reference.h5ad" "data.h5ad"      "result"         "0"             
 [5] "14"             "full"           "v2.subclass.l2" "x"             
 [9] "y"              "157.0"         
[1] "reading data"
[1] "csc"
[1] "reading reference"
[1] "csc"


Attaching package: ‘SparseM’

The following object is masked from ‘package:Matrix’:

    det

Error in `[<-.data.frame`(`*tmp*`, col, value = c("KC33_AAACCCACACGTTGGC",  : 
  replacement has 188620 rows, data has 1388642
Calls: read_reference -> read_adata -> read_df -> [<- -> [<-.data.frame
Execution halted

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[60], line 3
      1 import tacco as tc
----> 3 tc.tl.annotate(
      4     adata,
      5     adata_ref,
      6     method='RCTD',
      7     conda_env="[/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env)",
      8     annotation_key='v2.subclass.l2',
      9     result_key='v2.subclass.l2',
     10     assume_valid_counts=True,
     11 )

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:823](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=822), in annotate(adata, reference, annotation_key, result_key, counts_location, method, bisections, bisection_divisor, platform_iterations, normalize_to, annotation_prior, multi_center, multi_center_amplitudes, reconstruction_key, max_annotation, min_counts_per_gene, min_counts_per_cell, min_cells_per_gene, min_genes_per_cell, remove_constant_genes, remove_zero_cells, min_log2foldchange, min_expression, remove_mito, n_hvg, skip_checks, assume_valid_counts, return_reference, gene_keys, verbose, **kw_args)
    821     print('\n'.join(method_construction_info[::-1]))
    822 start = time.time()
--> 823 cell_type = _method(tdata, reference, annotation_key, annotation_prior, verbose)
    824 if verbose > 0:
    825     print(f'Finished annotation in {np.round(time.time() - start, 2)} seconds.')

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:384](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=383), in multi_center_annotation_method.<locals>._method(adata, reference, annotation_key, annotation_prior, verbose)
    381 nonlocal annotation_method, multi_center, prepare_reconstruction
    383 if multi_center is None or multi_center <= 1:
--> 384     cell_type = annotation_method(adata, reference, annotation_key, annotation_prior, verbose)
    385     if prepare_reconstruction is not None:
    386         prepare_reconstruction['annotation'] = cell_type.copy()

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:119](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=118), in annotation_method.<locals>._method(adata, reference, annotation_key, annotation_prior, verbose)
    115         cell_type = annotate(adata, reference, annotation_key, annotation_prior=_annotation_prior, **verbose_arg, **kw_args)
    117         #cell_type[/cell_type.sum](http://localhost:8889/cell_type.sum)(axis=1)[:,None]
    118     else:
--> 119         cell_type = annotate(adata, reference, annotation_key, **verbose_arg, **kw_args)
    121 else:
    122     try:

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py:273](http://localhost:8889/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py#line=272), in annotate_RCTD(adata, reference, annotation_key, counts_location, conda_env, x_coord_name, y_coord_name, doublet, min_ct, UMI_min_sigma, n_cores, working_directory, verbose)
    271         type_fractions = pd.read_csv(working_directory + result_file_name, sep='\t')
    272     else:
--> 273         raise Exception('RCTD did not work properly!')
    274 finally:
    275     if tempdir is not None:

Exception: RCTD did not work properly!"

I've tried cleaning up the cell IDs (making sure there are no duplicates, all unique, etc.) but I am still stumped as to what the problem might be.

**Comment by simonwm** [comment]
The issue might be connected either to the very large reference or to the csc matrices. The latter should be checked quickly: Try converting both the data and reference from csc to csr matrices.
To check whether it is about the reference size: try to randomly subsample the reference to something like 10k cells.

**Comment by reinertanalytics** [comment]
Hey, thanks for your response! Unfortunately neither of those options fixed the issue, as I am still getting the same error. Here's what it looks like now:

"Starting preprocessing
Annotation profiles were not found in `reference.varm["v2.subclass.l2"]`. Constructing reference profiles with `tacco.preprocessing.construct_reference_profiles` and default arguments...
Finished preprocessing in 0.68 seconds.
Starting annotation of data with shape (65551, 297) and a reference of shape (10000, 297) using the following wrapped method:
+- multi center: multi_center=None multi_center_amplitudes=True
   +- core: method=RCTD annotation_prior=None conda_env=/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env

[/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py:239](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py#line=238): ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata.obs[x_coord_name] = 0

 [1] "reference.h5ad" "data.h5ad"      "result"         "0"             
 [5] "14"             "full"           "v2.subclass.l2" "x"             
 [9] "y"              "157.0"         
[1] "reading data"
[1] "csr"
[1] "reading reference"
[1] "csr"


Attaching package: ‘SparseM’

The following object is masked from ‘package:Matrix’:

    det

Error in `[<-.data.frame`(`*tmp*`, col, value = c("NA", "KC84_CCTACGTCACCAGCGT-1",  : 
  replacement has 1347 rows, data has 10000
Calls: read_reference -> read_adata -> read_df -> [<- -> [<-.data.frame
Execution halted

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[14], line 3
      1 import tacco as tc
----> 3 tc.tl.annotate(
      4     adata,
      5     reference_subset,
      6     method='RCTD',
      7     conda_env="[/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env)",
      8     annotation_key='v2.subclass.l2',
      9     result_key='v2.subclass.l2',
     10     assume_valid_counts=True,
     11 )

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:823](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=822), in annotate(adata, reference, annotation_key, result_key, counts_location, method, bisections, bisection_divisor, platform_iterations, normalize_to, annotation_prior, multi_center, multi_center_amplitudes, reconstruction_key, max_annotation, min_counts_per_gene, min_counts_per_cell, min_cells_per_gene, min_genes_per_cell, remove_constant_genes, remove_zero_cells, min_log2foldchange, min_expression, remove_mito, n_hvg, skip_checks, assume_valid_counts, return_reference, gene_keys, verbose, **kw_args)
    821     print('\n'.join(method_construction_info[::-1]))
    822 start = time.time()
--> 823 cell_type = _method(tdata, reference, annotation_key, annotation_prior, verbose)
    824 if verbose > 0:
    825     print(f'Finished annotation in {np.round(time.time() - start, 2)} seconds.')

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:384](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=383), in multi_center_annotation_method.<locals>._method(adata, reference, annotation_key, annotation_prior, verbose)
    381 nonlocal annotation_method, multi_center, prepare_reconstruction
    383 if multi_center is None or multi_center <= 1:
--> 384     cell_type = annotation_method(adata, reference, annotation_key, annotation_prior, verbose)
    385     if prepare_reconstruction is not None:
    386         prepare_reconstruction['annotation'] = cell_type.copy()

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py:119](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_annotate.py#line=118), in annotation_method.<locals>._method(adata, reference, annotation_key, annotation_prior, verbose)
    115         cell_type = annotate(adata, reference, annotation_key, annotation_prior=_annotation_prior, **verbose_arg, **kw_args)
    117         #cell_type[/cell_type.sum](http://localhost:8888/cell_type.sum)(axis=1)[:,None]
    118     else:
--> 119         cell_type = annotate(adata, reference, annotation_key, **verbose_arg, **kw_args)
    121 else:
    122     try:

File [/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py:273](http://localhost:8888/opt/homebrew/Caskroom/miniconda/base/envs/tacco_env/lib/python3.12/site-packages/tacco/tools/_RCTD.py#line=272), in annotate_RCTD(adata, reference, annotation_key, counts_location, conda_env, x_coord_name, y_coord_name, doublet, min_ct, UMI_min_sigma, n_cores, working_directory, verbose)
    271         type_fractions = pd.read_csv(working_directory + result_file_name, sep='\t')
    272     else:
--> 273         raise Exception('RCTD did not work properly!')
    274 finally:
    275     if tempdir is not None:

Exception: RCTD did not work properly!"


I can also share what my adata looks like:

"AnnData object with n_obs × n_vars = 65551 × 300
    obs: 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'leiden', 'v2.subclass.l1', 'v2.subclass.l2', 'sample_id', 'library_id', 'Panel', 'PPID', 'Condition', 'sample_source', 'time_interval', 'region', 'full_id'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'pca', 'neighbors', 'hvg', 'umap', 'leiden', 'leiden_colors', 'spatial_neighbors', 'moranI', 'v2.subclass.l1_colors', 'v2.subclass.l2_colors'
    obsm: 'spatial', 'X_pca', 'X_umap', 'v2.subclass.l1', 'v2.subclass.l2'
    varm: 'PCs', 'v2.subclass.l1', 'v2.subclass.l2'
    layers: 'counts'
    obsp: 'distances', 'connectivities', 'spatial_connectivities', 'spatial_distances'"

Does this look like a python error or could it be something stemming from RCTD itself?

**Comment by simonwm** [comment]
The error comes from the R side, it looks like it is happening while constructing some R structures from the python-side adata.
This and a part of the error message (`c("NA", "KC84_CCTACGTCACCAGCGT-1", :`) made me wonder whether you might have a lot of observations which have the same name, like maybe many cells which have `"NA"` as value in `.obs.index`? During the construction of R-side structures all of those `"NA"` named cells would be overwritten to a single `"NA"` cell, reducing the cell count a lot in the `.obs` slot - and making it incompatible with the size of the count matrix. If so, then you could put the current `.obs.index` in some `.obs` column and create a new unique index, e.g. just stringified numbers.
